### ISSUE TITLE
Expression Manipulation and Img2Img Transfer

### ISSUE THREAD

**Issue by csimlinger** [georgeretsi/smirk#19]
Hi,

really inspiring work, amazing, thanks for publishing the code.

In your presentation video I saw that you combined your model with expression manipulation and image-to-image transfer:
https://youtu.be/8ZVgr41wxbk?si=uFuIGIdHRb10G3Ty&t=140

Is that part already implemented in the repo / any instructions on how to do that?
I am looking for a way to map the facial expressions of a 3D model onto a existing video.
My approach would have been to generate a 3DMM of the target video, manipulate the expression (morph targets or similar) and then transfer the 3DMM to the target video.

In would be really greatful for advice and input! 

Thanks!

**Comment by filby89** [comment]
Hey,
thank you very much for your interest in SMIRK and your kind words. To do what you want you can use demo.py with the flag `--use_smirk_generator`, but you will have to modify the expression coefficients before rendering in https://github.com/georgeretsi/smirk/blob/main/demo.py#L111. You can check e.g. here: https://github.com/georgeretsi/smirk/blob/main/src/smirk_trainer.py#L208 how we apply a random expression.

However, note that because the main focus of SMIRK is 3D reconstruction and not expression manipulation, so the reconstructed identity will not be that accurate. Let us know if you try it :)
