### ISSUE TITLE
No Face Detected

### ISSUE THREAD

**Issue by emlcpfx** [georgeretsi/smirk#22]
I have a piece of footage with one face, it's not occluded, it's very clearly in frame. Even if I set my confidence threshold really low on mediapipe_utils.py, it gives me No Face Detected, or put the face in the very wrong place. What do you think is going on?

**Comment by filby89** [comment]
Hey, I believe this could be caused because the mediapipe face detector is currently able to only recognize faces "near" the camera (https://ai.google.dev/edge/mediapipe/solutions/vision/face_detector). This face detector is used by mediapipe face mesh (https://ai.google.dev/edge/mediapipe/solutions/vision/face_landmarker).

One solution would be to use another face detector (e.g. https://github.com/hhj1897/face_detection) or crop the image around the face you want so that it is somehow "closer" to the camera.

**Comment by emlcpfx** [comment]
I'm pretty sure that's the problem, and they haven't released a model with the non-selfie version of Blazeface yet. Is the FaceMesh important, or is just the Face Detection? I'm wondering where in the code you could swap in the different detector.

**Comment by filby89** [comment]
It's not important, we actually only need face detection. If you check https://github.com/georgeretsi/smirk/blob/main/demo_video.py#L20 we use the keypoints to get a bounding box and use this to get the transform that crops the face. If you use another face detector you can get these values directly.

**Comment by emlcpfx** [comment]
Replacing with dlib worked, thank you.

**Comment by emlcpfx** [comment]
You were right-- it's best to crop down with another face detector, like dlib, and then pass that into mediapipe for the smoothest result. bypassing MP altogether didn't work, the 3DMM was all over the place.

Edit: This is just creating a badly tracked mess, I’m probably doing it wrong.

**Comment by emlcpfx** [comment]
I'm having a lot more luck using the full-range mediapipe model:

mp_face_detection = mp.solutions.face_detection
mp_drawing = mp.solutions.drawing_utils
face_detection = mp_face_detection.FaceDetection(model_selection=1, min_detection_confidence=0.25)

**Comment by emlcpfx** [comment]
I think we can close this thread with this—
 I replaced Mediapipe with Retinaface normal quality and it can handle most types of shots now.

Let me know if you’d like to implement that.
